"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "composeApp"

"preserve_hierarchy": true

"files": [
  {
    "source": "src/commonMain/composeResources/values/strings.xml",
    "translation": "src/commonMain/composeResources/values-%two_letters_code%/strings.xml"
  }
]