name: Build Application

on:
  push:
  workflow_dispatch:

jobs:
    build:
      strategy:
        fail-fast: false
        matrix:
          os: [ ubuntu-20.04, macos-14, windows-2022 ]
          gradle: [8.9]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: 17
            distribution: temurin
        - name: Build Multiplatform project
          shell: bash
          run: ./gradlew assemble
        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: debug-artifacts-${{ matrix.os }}-${{ github.run_number }}
            path: |
              composeApp/build/outputs/apk/debug/*.apk
