name: Build Application

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
    build:
      strategy:
        fail-fast: false
        matrix:
          os: [ ubuntu-20.04, macos-14, windows-2022 ]
          gradle: [ 7.4, 8.10.2 ]
          agp: [ 8.1.0, 8.5.0, 8.8.0-alpha08 ]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: temurin
        - name: Build Multiplatform project
          shell: bash
          run: ./gradlew assemble
        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: debug-artifacts
            path: |
              composeApp/build/outputs/apk/debug/*.apk
