name: Build Application

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: macOS-latest

    strategy:
      matrix:
        platform: [ android, ios ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ matrix.platform }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build Android
        if: matrix.platform == 'android'
        run: ./gradlew assembleDebug

      - name: Build iOS
        if: matrix.platform == 'ios'
        run: ./gradlew :composeApp:linkDebugFrameworkIosFat

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-artifacts
          path: |
            composeApp/build/outputs/apk/debug/*.apk
